// Jaehong An portfolio works manifest
// Add new works by copying one object and changing idx/title/poster paths.
// Use video for local playback, or externalUrl for works hosted elsewhere.
window.JAEHONG_WORKS = [
  {
    idx: "01",
    title: "MSC: CRM 90",
    desc: "기억이 삭제된 채 90년의 냉동형을 선고받은 한 인물이 2167년 해동과 재활을 앞두고 자신의 삶을 되짚는다. 미래의 형벌 시스템과 노년 여성의 증언이 교차하는 가운데, 작품은 기억이 지워진 뒤에도 한 사람의 삶과 관계가 남을 수 있는지 묻는다. 형벌과 돌봄, 기억의 소유권을 둘러싼 이야기를 통해 한 사람을 다시 사회로 돌려보낸다는 말의 의미를 되짚는다.",
    descEn: "A woman sentenced to ninety years in cryonic confinement with her memory erased looks back on her life before her scheduled thawing and rehabilitation in 2167. As her testimony intersects with the apparatus of a future penal system, the work asks whether a person's life and relationships can remain after memory has been removed. It considers punishment, care, the ownership of memory, and what it means to return someone to society.",
    fullDesc: "MSC: CRM 90\nJaehong An, 2026\nAI Generated · Single-channel Video\n16:9\nUNCOMMON OPEN CALL\n언커먼 갤러리\n2026.07.02 - 2026.07.16\n\n기억이 삭제된 채 90년의 냉동형을 선고받은 한 인물이 2167년 해동과 재활을 앞두고 자신의 삶을 되짚는다. 미래의 형벌 시스템과 노년 여성의 증언이 교차하는 가운데, 작품은 기억이 지워진 뒤에도 한 사람의 삶과 관계가 남을 수 있는지 묻는다. 형벌과 돌봄, 기억의 소유권을 둘러싼 이야기를 통해 한 사람을 다시 사회로 돌려보낸다는 말의 의미를 되짚는다.",
    fullDescEn: "MSC: CRM 90\nJaehong An, 2026\nAI Generated · Single-channel Video\n16:9\nUNCOMMON OPEN CALL\nUncommon Gallery\nJuly 2-16, 2026\n\nA woman sentenced to ninety years in cryonic confinement with her memory erased looks back on her life before her scheduled thawing and rehabilitation in 2167. As her testimony intersects with the apparatus of a future penal system, the work asks whether a person's life and relationships can remain after memory has been removed. It considers punishment, care, the ownership of memory, and what it means to return someone to society.",
    year: "2026.07",
    medium: "AI Generated · Single-channel Video",
    duration: "9′26″",
    aspect: "16:9",
    layout: "wide",
    context: "UNCOMMON OPEN CALL\n언커먼 갤러리\n2026.07.02 - 2026.07.16",
    contextEn: "UNCOMMON OPEN CALL\nUncommon Gallery\nJuly 2-16, 2026",
    caption: "UNCOMMON OPEN CALL · Uncommon Gallery, 2026",
    frameCaption: "UNCOMMON OPEN CALL",
    poster: "assets/posters/work-msc-crm-90.jpg",
    externalUrl: "https://youtu.be/iT_cagP-TFw",
    externalLabel: "Watch on YouTube →",
    externalLabelKo: "YouTube에서 보기 →"
  },
  {
    idx: "02",
    title: "SaRangHae - The Last Message Before the End of Civilization",
    desc: "〈SaRangHae - The Last Message Before the End of Civilization〉은 한국어 ‘사랑해’를 인류 문명의 끝자락에서 남겨지는 마지막 메시지로 상상한 대형 디지털 미디어 작품이다. 작가는 2024년, 앞으로 세계에 좋지 않은 일들이 벌어질 것 같다는 불길한 예감을 느꼈고, 뉴욕 타임스퀘어라는 거대한 공적 공간에서 어떤 말을 외쳐야 할지 고민했다. 그 끝에 선택한 말은 구호도 경고도 선언도 아닌, 가장 사적이고 연약한 말인 ‘사랑해’였다.\n\n생성형 AI로 구현된 디지털 아바타는 화면 속에서 ‘사랑해’라고 말하지만, 대형 전광판이라는 상영 환경 속에서 그 목소리는 실제 현장에 들리지 않는다. 원본 영상에는 사운드가 존재하지만, 타임스퀘어의 군중과 광고, 도시의 소음 속에서 이 발화는 무음의 외침이 된다. 작가가 현장에서 작품을 아카이빙했을 때, 사람들은 그 영상을 거의 바라보지 않았다. 그 장면은 작품의 외부 조건이 아니라 작품의 일부가 된다. 사랑은 외쳐지지만 들리지 않고, 존재는 말하지만 세계는 지나쳐 간다.\n\n작품 속 미래적 장면들은 외계 행성 탐사, 초연결 네트워크, 지속가능한 연구 시설, 우주여행의 이미지로 구성되어 있다. 그러나 이 미래의 풍경은 낙관적 전망이라기보다, 전쟁과 혐오, 환경 파괴, 증오가 확산되는 현실과 충돌하며 불안한 대비를 이룬다. 2026년 현재 더욱 첨예해진 국제적 갈등 속에서, 2024년에 던져진 ‘사랑해’라는 말은 뒤늦게 도착한 경고처럼 보인다. 이 작품은 사랑이 세상을 구할 수 있다고 쉽게 말하지 않는다. 오히려 사랑마저 들리지 않게 된 세계에서, 우리가 무엇을 잃어가고 있는지를 묻는다.",
    descEn: "SaRangHae - The Last Message Before the End of Civilization is a large-scale digital media work that imagines the Korean phrase ‘사랑해’ or ‘I love you’ as the final message left at the edge of civilization.\n\nCreated in 2024, the work began with a quiet sense of foreboding. The artist felt that something dark was gathering in the world, that conflicts, hatred, and violence might soon intensify beyond familiar boundaries. Faced with the question of what kind of cry should be sent into the public heart of New York, he chose neither a warning nor a slogan, but the most intimate and fragile phrase: ‘I love you.’\n\nIn the work, an AI-generated digital avatar repeatedly speaks the word ‘SaRangHae.’ The original video contains sound, yet the conditions of its presentation on a large LED screen in Times Square made the voice inaudible in the actual site. The figure speaks, but the voice does not reach the crowd. Love is uttered, yet it disappears into the noise of the city, the flow of advertisements, and the indifference of passersby.\n\nWhen the artist documented the work in Times Square, he observed that almost no one stopped to look at the image. This scene became inseparable from the work itself. The piece was no longer only about the delivery of a message, but about a being calling out love into a world that no longer listens. Its silence, distance, and failure to arrive became part of its meaning.\n\nThe futuristic scenes within the work, including alien exploration, hyper-connected networks, sustainable research facilities, and space travel, appear at first as visions of progress. Yet they are placed against the growing realities of war, ecological collapse, social hostility, and collective exhaustion. Seen from 2026, the word chosen in 2024 now carries a more urgent resonance. What once appeared as a simple declaration of love begins to read as a delayed warning, a fragile signal sent before the storm became visible.\n\nThe work does not claim that love can easily save the world. Instead, it asks what happens when even love can no longer be heard. In a civilization saturated with images, noise, and conflict, SaRangHae becomes a silent cry, a final attempt to speak the one word that might still matter before everything collapses.",
    fullDesc: "Jaehong An, 2024\nAI Generated · Single-channel Video\n3312×936 px / Display size 26′ × 94′\nLIGHT VISIONS: NEW YORK\nBILLBOARDS: 1619 Broadway WS 20ft N/O 49th St F/S\n2024.09.02 - 2024.09.08\n\n〈SaRangHae - The Last Message Before the End of Civilization〉은 한국어 ‘사랑해’를 인류 문명의 끝자락에서 남겨지는 마지막 메시지로 상상한 대형 디지털 미디어 작품이다. 작가는 2024년, 앞으로 세계에 좋지 않은 일들이 벌어질 것 같다는 불길한 예감을 느꼈고, 뉴욕 타임스퀘어라는 거대한 공적 공간에서 어떤 말을 외쳐야 할지 고민했다. 그 끝에 선택한 말은 구호도 경고도 선언도 아닌, 가장 사적이고 연약한 말인 ‘사랑해’였다.\n\n생성형 AI로 구현된 디지털 아바타는 화면 속에서 ‘사랑해’라고 말하지만, 대형 전광판이라는 상영 환경 속에서 그 목소리는 실제 현장에 들리지 않는다. 원본 영상에는 사운드가 존재하지만, 타임스퀘어의 군중과 광고, 도시의 소음 속에서 이 발화는 무음의 외침이 된다. 작가가 현장에서 작품을 아카이빙했을 때, 사람들은 그 영상을 거의 바라보지 않았다. 그 장면은 작품의 외부 조건이 아니라 작품의 일부가 된다. 사랑은 외쳐지지만 들리지 않고, 존재는 말하지만 세계는 지나쳐 간다.\n\n작품 속 미래적 장면들은 외계 행성 탐사, 초연결 네트워크, 지속가능한 연구 시설, 우주여행의 이미지로 구성되어 있다. 그러나 이 미래의 풍경은 낙관적 전망이라기보다, 전쟁과 혐오, 환경 파괴, 증오가 확산되는 현실과 충돌하며 불안한 대비를 이룬다. 2026년 현재 더욱 첨예해진 국제적 갈등 속에서, 2024년에 던져진 ‘사랑해’라는 말은 뒤늦게 도착한 경고처럼 보인다. 이 작품은 사랑이 세상을 구할 수 있다고 쉽게 말하지 않는다. 오히려 사랑마저 들리지 않게 된 세계에서, 우리가 무엇을 잃어가고 있는지를 묻는다.",
    fullDescEn: "Jaehong An, 2024\nAI Generated · Single-channel Video\n3312×936 px / Display size 26′ × 94′\nLIGHT VISIONS: NEW YORK\nBILLBOARDS: 1619 Broadway WS 20ft N/O 49th St F/S\nSeptember 2-8, 2024\n\nSaRangHae - The Last Message Before the End of Civilization is a large-scale digital media work that imagines the Korean phrase ‘사랑해’ or ‘I love you’ as the final message left at the edge of civilization.\n\nCreated in 2024, the work began with a quiet sense of foreboding. The artist felt that something dark was gathering in the world, that conflicts, hatred, and violence might soon intensify beyond familiar boundaries. Faced with the question of what kind of cry should be sent into the public heart of New York, he chose neither a warning nor a slogan, but the most intimate and fragile phrase: ‘I love you.’\n\nIn the work, an AI-generated digital avatar repeatedly speaks the word ‘SaRangHae.’ The original video contains sound, yet the conditions of its presentation on a large LED screen in Times Square made the voice inaudible in the actual site. The figure speaks, but the voice does not reach the crowd. Love is uttered, yet it disappears into the noise of the city, the flow of advertisements, and the indifference of passersby.\n\nWhen the artist documented the work in Times Square, he observed that almost no one stopped to look at the image. This scene became inseparable from the work itself. The piece was no longer only about the delivery of a message, but about a being calling out love into a world that no longer listens. Its silence, distance, and failure to arrive became part of its meaning.\n\nThe futuristic scenes within the work, including alien exploration, hyper-connected networks, sustainable research facilities, and space travel, appear at first as visions of progress. Yet they are placed against the growing realities of war, ecological collapse, social hostility, and collective exhaustion. Seen from 2026, the word chosen in 2024 now carries a more urgent resonance. What once appeared as a simple declaration of love begins to read as a delayed warning, a fragile signal sent before the storm became visible.\n\nThe work does not claim that love can easily save the world. Instead, it asks what happens when even love can no longer be heard. In a civilization saturated with images, noise, and conflict, SaRangHae becomes a silent cry, a final attempt to speak the one word that might still matter before everything collapses.",
    year: "2024.09",
    medium: "AI Generated · Single-channel Video",
    duration: "20 sec",
    aspect: "3312×936 px / 26′×94′",
    layout: "wide",
    context: "LIGHT VISIONS: NEW YORK\nBILLBOARDS: 1619 Broadway WS 20ft N/O 49th St F/S\n2024.09.02 - 2024.09.08",
    contextEn: "LIGHT VISIONS: NEW YORK\nBILLBOARDS: 1619 Broadway WS 20ft N/O 49th St F/S\nSeptember 2-8, 2024",
    caption: "LIGHT VISIONS: NEW YORK · Times Square, 2024",
    frameCaption: "LIGHT VISIONS: NEW YORK",
    video: "media/web/work-00-web-lite.mp4",
    poster: "assets/posters/work-00-web.jpg"
  },
  {
    idx: "03",
    title: "A HUNDRED POSSIBILITIES & VENECITE",
    desc: "생성형 인공지능으로 만들어진 사실적인 가상 인물들을 휴먼 스케일의 LED 화면으로 광화문광장에 세운 디지털 아트 설치 작업이다. 가까운 미래에서 온 듯한 인물들은 각자의 서사를 품은 채 현실 공간에 놓이고, 디지털 세계와 인간 세계 사이의 경계를 조용히 흐린다.\n\n현장에는 생성형 AI를 활용한 여러 이미지들이 빠른 움직임과 강한 시각 효과를 만들어내고 있었다. 그 사이에서 이 작업은 오히려 정적인 구성과 절제된 움직임으로 관람자의 시선을 붙잡았다. 거의 멈춰 있는 듯한 인물들은 낯선 존재감을 만들었고, 어린이 관람객들이 작품 앞에 오래 머물며 집중하는 장면도 목격되었다.\n\n과거와 현재, 미래가 겹쳐 있는 광화문광장에서 작업은 인공지능 기술과 예술이 만들어내는 새로운 현실감, 그리고 인간과 비인간 존재가 함께 놓일 미래의 풍경을 바라본다.",
    descEn: "A digital art installation that presented realistic virtual figures generated with AI on human-scale LED screens in Gwanghwamun Square. These figures seem to belong to a near future, yet they enter a public urban space with their own latent narratives, quietly blurring the boundary between the digital world and the human one.\n\nAmid other generative AI works that emphasized rapid movement and intense visual effects, this piece held attention through stillness and restrained motion. The nearly motionless figures created a strange presence, and children at the site were seen lingering in front of the work, looking closely.\n\nSet in Gwanghwamun Square, where past, present, and future overlap, the work considers a new sense of reality shaped by AI and art, and imagines a future landscape in which human and non-human presences coexist.",
    fullDesc: "〈A HUNDRED POSSIBILITIES & VENECITE〉\nJaehong An, 2023\nAI Generated · Single-channel Video\n960×1920 px / 1m × 2m vertical LED screen\n2023 서울라이트 광화문\n광화문광장 육조마당\n2023.12.22 - 2024.01.21\n\n생성형 인공지능으로 만들어진 사실적인 가상 인물들을 휴먼 스케일의 LED 화면으로 광화문광장에 세운 디지털 아트 설치 작업이다. 가까운 미래에서 온 듯한 인물들은 각자의 서사를 품은 채 현실 공간에 놓이고, 디지털 세계와 인간 세계 사이의 경계를 조용히 흐린다.\n\n현장에는 생성형 AI를 활용한 여러 이미지들이 빠른 움직임과 강한 시각 효과를 만들어내고 있었다. 그 사이에서 이 작업은 오히려 정적인 구성과 절제된 움직임으로 관람자의 시선을 붙잡았다. 거의 멈춰 있는 듯한 인물들은 낯선 존재감을 만들었고, 어린이 관람객들이 작품 앞에 오래 머물며 집중하는 장면도 목격되었다.\n\n과거와 현재, 미래가 겹쳐 있는 광화문광장에서 작업은 인공지능 기술과 예술이 만들어내는 새로운 현실감, 그리고 인간과 비인간 존재가 함께 놓일 미래의 풍경을 바라본다.",
    fullDescEn: "A HUNDRED POSSIBILITIES & VENECITE\nJaehong An, 2023\nAI Generated · Single-channel Video\n960×1920 px / 1m × 2m vertical LED screen\n2023 SEOULIGHT GWANGHWAMUN\nYukjo Madang, Gwanghwamun Square, Seoul\nDecember 22, 2023 - January 21, 2024\n\nA digital art installation that presented realistic virtual figures generated with AI on human-scale LED screens in Gwanghwamun Square. These figures seem to belong to a near future, yet they enter a public urban space with their own latent narratives, quietly blurring the boundary between the digital world and the human one.\n\nAmid other generative AI works that emphasized rapid movement and intense visual effects, this piece held attention through stillness and restrained motion. The nearly motionless figures created a strange presence, and children at the site were seen lingering in front of the work, looking closely.\n\nSet in Gwanghwamun Square, where past, present, and future overlap, the work considers a new sense of reality shaped by AI and art, and imagines a future landscape in which human and non-human presences coexist.",
    year: "2023.12",
    medium: "AI Generated · Single-channel Video",
    duration: "0′53″",
    aspect: "960×1920 px / 1m×2m",
    context: "2023 서울라이트 광화문\n광화문광장 육조마당\n2023.12.22 - 2024.01.21",
    contextEn: "2023 SEOULIGHT GWANGHWAMUN\nYukjo Madang, Gwanghwamun Square, Seoul\nDecember 22, 2023 - January 21, 2024",
    caption: "2023 SEOULIGHT GWANGHWAMUN · Gwanghwamun Square",
    frameCaption: "2023 SEOULIGHT GWANGHWAMUN",
    video: "media/web/work-seoulight-2023-web.mp4",
    poster: "assets/posters/work-seoulight-2023.jpg"
  },
  {
    idx: "04",
    title: "Elevate",
    desc: "외모 중심의 기준과 반복되는 자기 평가를 엘리베이터의 상승과 하강 구조로 다룬 단편이다. 불안한 표정의 여성이 엘리베이터를 타고 성형 클리닉으로 향한다. 결제와 서류 작성, 수술을 마친 뒤 거울 속 달라진 얼굴을 확인하고 만족하지만, 건물 밖 미디어 화면에는 더 아름다운 얼굴들이 등장한다. 만족은 곧 새로운 기준과 결핍으로 바뀌고, 같은 여정을 반복할수록 얼굴은 점차 왜곡된다. 위로 움직이는 엘리베이터의 운동과 자아가 소멸하는 인물의 방향을 대비시킨다.\n\n〈Elevate〉는 신해윤과 공동 제작했으며, Runway Gen:48 Aleph Edition의 48시간 제작 조건 안에서 완성되었다. 2025년 People's Choice Honoree로 선정되었다.",
    descEn: "Elevate uses the repeated ascent and descent of an elevator to examine appearance-based standards and cycles of self-evaluation. A woman enters an elevator and travels to a cosmetic clinic. After payment, paperwork, and surgery, she is satisfied with her altered reflection, but media screens outside present faces that establish another standard. As she repeats the journey, her face becomes increasingly distorted. The film contrasts the elevator's upward motion with the character's movement toward the loss of self.\n\nCo-created with Haeyun Shin, the film was completed within the 48-hour production period of Runway Gen:48 Aleph Edition and was named a People's Choice Honoree in 2025.",
    fullDescEn: "Elevate\nJaehong An & Haeyun Shin, 2025\nAI Generated · Single-channel Video\n4096×2304 px\nRunway GEN:48 ALEPH EDITION · People's Choice Honoree\nRunway Gen:48 Aleph Edition\nAugust 23-25, 2025\n\nElevate uses the repeated ascent and descent of an elevator to examine appearance-based standards and cycles of self-evaluation. A woman enters an elevator and travels to a cosmetic clinic. After payment, paperwork, and surgery, she is satisfied with her altered reflection, but media screens outside present faces that establish another standard. As she repeats the journey, her face becomes increasingly distorted. The film contrasts the elevator's upward motion with the character's movement toward the loss of self.\n\nCo-created with Haeyun Shin, the film was completed within the 48-hour production period of Runway Gen:48 Aleph Edition and was named a People's Choice Honoree in 2025.",
    year: "2025.08",
    medium: "AI Generated · Single-channel Video",
    duration: "3′11″",
    aspect: "4096×2304 px",
    layout: "wide",
    context: "Runway Gen:48 Aleph Edition\n2025.08.23 - 2025.08.25",
    contextEn: "Runway Gen:48 Aleph Edition\nAugust 23-25, 2025",
    caption: "Runway GEN:48 ALEPH EDITION · People's Choice Honoree",
    frameCaption: "Runway GEN:48 ALEPH EDITION",
    award: "Runway GEN:48 ALEPH EDITION · People's Choice Honoree",
    authors: "Jaehong An & Haeyun Shin",
    credit: "공동 제작 · 안재홍 · 신해윤",
    creditEn: "Co-created by Jaehong An & Haeyun Shin",
    poster: "assets/posters/work-04.webp",
    externalUrl: "https://runwayml.com/gen48?film=elevate",
    externalLabel: "Watch on Runway →",
    externalLabelKo: "Runway에서 보기 →",
    youtubeId: "bnU5NJ90peU",
    fullDesc: "Elevate\nJaehong An & Haeyun Shin, 2025\nAI Generated · Single-channel Video\n4096×2304 px\nRunway GEN:48 ALEPH EDITION · People's Choice Honoree\nRunway Gen:48 Aleph Edition\n2025.08.23 - 2025.08.25\n\n외모 중심의 기준과 반복되는 자기 평가를 엘리베이터의 상승과 하강 구조로 다룬 단편이다. 불안한 표정의 여성이 엘리베이터를 타고 성형 클리닉으로 향한다. 결제와 서류 작성, 수술을 마친 뒤 거울 속 달라진 얼굴을 확인하고 만족하지만, 건물 밖 미디어 화면에는 더 아름다운 얼굴들이 등장한다. 만족은 곧 새로운 기준과 결핍으로 바뀌고, 같은 여정을 반복할수록 얼굴은 점차 왜곡된다. 위로 움직이는 엘리베이터의 운동과 자아가 소멸하는 인물의 방향을 대비시킨다.\n\n〈Elevate〉는 신해윤과 공동 제작했으며, Runway Gen:48 Aleph Edition의 48시간 제작 조건 안에서 완성되었다. 2025년 People's Choice Honoree로 선정되었다."
  },
  {
    idx: "05",
    title: "The Return of Love",
    desc: "2030년, 인류가 기술적 특이점을 넘어 질병과 빈곤, 죽음을 극복한 사회를 배경으로 한다. 한 젊은 활동가는 거리에서 사랑과 인간성의 회복을 주장한다. 그녀는 죽음의 부재가 불평등을 영속시키고, 유한한 삶이 지녔던 가치와 사랑의 의미를 약화시켰다고 말한다. 작품은 기술적 풍요가 삶의 유한성, 불평등, 사랑과 연대의 개념을 어떻게 바꾸는지 살핀다.",
    descEn: "Set in 2030, the work depicts a society that has crossed the technological singularity and overcome disease, poverty, and death. A young activist takes to the streets to call for the recovery of love and humanity. She argues that the absence of death has perpetuated inequality and weakened the value once associated with finite life. The work examines how technological abundance alters ideas of mortality, inequality, love, and solidarity.",
    year: "2025.09",
    medium: "AI Generated · Single-channel Video",
    duration: "1′03″",
    aspect: "1076×1920 px / CRT 4:3",
    context: "We Were Here (안재홍 독립전시)\n서울특별시 은평구 응암로 12길 17, 구 응암공업사\n2025.10.21 - 2025.11.02",
    contextEn: "We Were Here, independent exhibition organized by Jaehong An\nFormer Eungam Industrial Workshop, 17 Eungam-ro 12-gil, Eunpyeong-gu, Seoul\nOctober 21 - November 2, 2025",
    caption: "We Were Here · CRT single-channel video",
    frameCaption: "We Were Here",
    video: "media/web/work-04-return-of-love-web.mp4",
    poster: "assets/posters/work-04-return-of-love-web.jpg",
    fullDesc: "The Return of Love\nJaehong An, 2025\nAI Generated · Single-channel Video\n1076×1920 px / CRT 4:3\nWe Were Here (안재홍 독립전시)\n서울특별시 은평구 응암로 12길 17, 구 응암공업사\n2025.10.21 - 2025.11.02\n\n2030년, 인류가 기술적 특이점을 넘어 질병과 빈곤, 죽음을 극복한 사회를 배경으로 한다. 한 젊은 활동가는 거리에서 사랑과 인간성의 회복을 주장한다. 그녀는 죽음의 부재가 불평등을 영속시키고, 유한한 삶이 지녔던 가치와 사랑의 의미를 약화시켰다고 말한다. 작품은 기술적 풍요가 삶의 유한성, 불평등, 사랑과 연대의 개념을 어떻게 바꾸는지 살핀다.",
    fullDescEn: "The Return of Love\nJaehong An, 2025\nAI Generated · Single-channel Video\n1076×1920 px / CRT 4:3\nWe Were Here, independent exhibition organized by Jaehong An\nFormer Eungam Industrial Workshop, 17 Eungam-ro 12-gil, Eunpyeong-gu, Seoul\nOctober 21 - November 2, 2025\n\nSet in 2030, the work depicts a society that has crossed the technological singularity and overcome disease, poverty, and death. A young activist takes to the streets to call for the recovery of love and humanity. She argues that the absence of death has perpetuated inequality and weakened the value once associated with finite life. The work examines how technological abundance alters ideas of mortality, inequality, love, and solidarity.",
    layout: "four-three"
  },
  {
    idx: "06",
    title: "What is Real? What is Human?",
    desc: "1940년에 개봉된 찰리 채플린의 영화 〈위대한 독재자〉를, 특히 마지막 연설을 중심으로 현재의 기술문명의 흐름 안에서 다시 소환한 작업이다. 채플린이 제작, 각본, 감독, 주연을 맡은 이 반파시즘 풍자 영화가 전쟁과 파시즘의 시대에 인간성과 자유의 회복을 호소했다면, 이 작품은 그 텍스트가 오늘날에도 여전히 유효한지를 묻는다.\n\n작품 속 스피치는 온전한 인간이 아니라 기계화된 인간의 얼굴과 목소리를 통해 전달된다. 인간성에 대한 오래된 문장이 비인간적 기술의 표면을 통과할 때, 메시지는 단순한 인용이 아니라 현대 문명의 역설을 드러내는 장면이 된다. 무엇이 인간을 인간답게 하는지, 왜 우리는 아직도 기계를 모방하려 하는지, 그리고 그 질문을 누가 말하고 있는지를 확인시킨다.",
    descEn: "This work recalls Charlie Chaplin’s 1940 film The Great Dictator, especially its final speech, within the current flow of technological civilization. Written, directed, produced, and performed by Chaplin, the anti-fascist satire appealed for the recovery of humanity and freedom in an age of war and fascism. This work asks whether that text still remains valid today.\n\nThe speech is delivered not through an intact human body, but through the face and voice of a mechanized human figure. When an old sentence about humanity passes through the surface of nonhuman technology, the message becomes less a quotation than a scene that exposes the paradox of modern civilization. It asks what makes a human human, why we still try to imitate machines, and who is now speaking that question.",
    year: "2025.12",
    medium: "AI Generated · Single-channel Video",
    duration: "0′29″",
    aspect: "1080×1920 px",
    fullDesc: "What is Real? What is Human?\nJaehong An, 2025\nAI Generated · Single-channel Video\n1080×1920 px\n\n1940년에 개봉된 찰리 채플린의 영화 〈위대한 독재자〉를, 특히 마지막 연설을 중심으로 현재의 기술문명의 흐름 안에서 다시 소환한 작업이다. 채플린이 제작, 각본, 감독, 주연을 맡은 이 반파시즘 풍자 영화가 전쟁과 파시즘의 시대에 인간성과 자유의 회복을 호소했다면, 이 작품은 그 텍스트가 오늘날에도 여전히 유효한지를 묻는다.\n\n작품 속 스피치는 온전한 인간이 아니라 기계화된 인간의 얼굴과 목소리를 통해 전달된다. 인간성에 대한 오래된 문장이 비인간적 기술의 표면을 통과할 때, 메시지는 단순한 인용이 아니라 현대 문명의 역설을 드러내는 장면이 된다. 무엇이 인간을 인간답게 하는지, 왜 우리는 아직도 기계를 모방하려 하는지, 그리고 그 질문을 누가 말하고 있는지를 확인시킨다.",
    fullDescEn: "What is Real? What is Human?\nJaehong An, 2025\nAI Generated · Single-channel Video\n1080×1920 px\n\nThis work recalls Charlie Chaplin’s 1940 film The Great Dictator, especially its final speech, within the current flow of technological civilization. Written, directed, produced, and performed by Chaplin, the anti-fascist satire appealed for the recovery of humanity and freedom in an age of war and fascism. This work asks whether that text still remains valid today.\n\nThe speech is delivered not through an intact human body, but through the face and voice of a mechanized human figure. When an old sentence about humanity passes through the surface of nonhuman technology, the message becomes less a quotation than a scene that exposes the paradox of modern civilization. It asks what makes a human human, why we still try to imitate machines, and who is now speaking that question.",
    video: "media/web/work-02-web.mp4",
    poster: "assets/posters/work-02.jpg"
  },
  {
    idx: "07",
    title: "Circuits of Grace",
    desc: "무뇌증으로 대뇌 없이 태어난 여성이 기계 뇌와 인공지능 소프트웨어를 통해 걷고, 말하고, 생각하고, 감정을 느끼게 된다는 설정에서 출발한다. 어린 시절 따돌림과 취업 차별을 경험한 뒤, 자신의 삶을 축복으로 받아들이고 수도자가 되어 비슷한 어려움을 겪는 아이들을 돌본다. 성당에서 자신의 생존을 축복으로 해석하고 아이들을 위해 기도하는 독백을 통해 기술과 신앙, 장애 경험과 돌봄이 교차하는 방식을 다룬다.",
    descEn: "The work begins with a fictional premise: a woman born with anencephaly gains the ability to walk, speak, think, and feel through a mechanical brain and artificial intelligence software. After experiencing bullying and employment discrimination, she interprets her continued life as a blessing and becomes a nun who supports children facing similar circumstances. Her monologue in a cathedral addresses survival, faith, and care, while the work examines the intersection of technology, disability, and religious belief.",
    year: "2025.10",
    medium: "AI Generated · Single-channel Video",
    duration: "1′15″",
    aspect: "1088×1904 px / CRT 4:3",
    context: "We Were Here (안재홍 독립전시)\n서울특별시 은평구 응암로 12길 17, 구 응암공업사\n2025.10.21 - 2025.11.02",
    contextEn: "We Were Here, independent exhibition organized by Jaehong An\nFormer Eungam Industrial Workshop, 17 Eungam-ro 12-gil, Eunpyeong-gu, Seoul\nOctober 21 - November 2, 2025",
    caption: "We Were Here · CRT single-channel video",
    frameCaption: "We Were Here",
    video: "media/web/work-06-circuits-of-grace-web.mp4",
    poster: "assets/posters/work-06-circuits-of-grace-web.jpg",
    fullDesc: "Circuits of Grace\nJaehong An, 2025\nAI Generated · Single-channel Video\n1088×1904 px / CRT 4:3\nWe Were Here (안재홍 독립전시)\n서울특별시 은평구 응암로 12길 17, 구 응암공업사\n2025.10.21 - 2025.11.02\n\n무뇌증으로 대뇌 없이 태어난 여성이 기계 뇌와 인공지능 소프트웨어를 통해 걷고, 말하고, 생각하고, 감정을 느끼게 된다는 설정에서 출발한다. 어린 시절 따돌림과 취업 차별을 경험한 뒤, 자신의 삶을 축복으로 받아들이고 수도자가 되어 비슷한 어려움을 겪는 아이들을 돌본다. 성당에서 자신의 생존을 축복으로 해석하고 아이들을 위해 기도하는 독백을 통해 기술과 신앙, 장애 경험과 돌봄이 교차하는 방식을 다룬다.",
    fullDescEn: "Circuits of Grace\nJaehong An, 2025\nAI Generated · Single-channel Video\n1088×1904 px / CRT 4:3\nWe Were Here, independent exhibition organized by Jaehong An\nFormer Eungam Industrial Workshop, 17 Eungam-ro 12-gil, Eunpyeong-gu, Seoul\nOctober 21 - November 2, 2025\n\nThe work begins with a fictional premise: a woman born with anencephaly gains the ability to walk, speak, think, and feel through a mechanical brain and artificial intelligence software. After experiencing bullying and employment discrimination, she interprets her continued life as a blessing and becomes a nun who supports children facing similar circumstances. Her monologue in a cathedral addresses survival, faith, and care, while the work examines the intersection of technology, disability, and religious belief.",
    layout: "four-three"
  },
  {
    idx: "08",
    title: "The Breath Keepers",
    desc: "태어날 때부터 눈이 보이지 않았던 것은 아니다. 우연히 일어난 단 한 번의 사고 이후, 아무것도 볼 수가 없었다. 지금의 시대에는 새로운 아이를 만드는 일이 너무 쉬워졌고, 고장난 아이는 쉽게 버려진다. 나는 부서진 기계들이 쌓여 있는 폐기물 구역으로 보내졌다. 그곳에서 나처럼 거의 앞을 볼 수 없던 한 여성 무속인이 나를 발견했다. 그녀는 나를 산 정상의 움막으로 데려갔고, 시각이 아닌 감각으로 살아가는 법을 가르쳐주었다.\n\n그녀의 집단은 불행을 지우려 하지 않는다. 대신 고통을 품은 채 무너지지 않고 서는 훈련을 평생 이어나간다. 무속인들은 남은 숨결과 기억, 생존의 비밀을 어린 아이들에게 넘겨준 뒤, 비워진 몸으로 조용히 죽음을 맞이한다. 그녀는 떠나기 전, 자신을 이을 무속인으로 나를 지명했다. 모두가 기계에 의존해 살아가지만, 길을 잃은 몇몇 사람들은 가끔 거대한 도시를 뒤로하고 이 산 정상의 집을 향해 길고 가파른 길을 오른다. 숨이 목 끝까지 차올라 거세게 울릴 때까지.",
    descEn: "I was not born blind. After a single accident that happened by chance, I could no longer see anything. In this age, making new children has become far too easy, and a faulty child is easily thrown away. I was sent to a waste zone piled with broken machines. There, a woman shaman who could barely see, like me, found me. She took me to a hut on the mountaintop and taught me how to live through senses other than sight.\n\nHer group does not try to erase misfortune. Instead, they spend their lives training to stand without breaking while carrying pain. Shamans hand over their remaining breath, memories, and secrets of survival to children, then quietly greet death in emptied bodies. Before she left, she named me as the shaman who would follow after her. Everyone lives depending on machines, but a few of the lost sometimes leave the enormous city behind and climb the long, steep path toward this house on the mountaintop, until breath rises to their throats and pounds fiercely.",
    year: "2025.11",
    medium: "AI Generated · Single-channel Video",
    duration: "2′34″",
    aspect: "2160×3840 px",
    fullDesc: "The Breath Keepers\nJaehong An, 2025\nAI Generated · Single-channel Video\n2160×3840 px\n\n태어날 때부터 눈이 보이지 않았던 것은 아니다. 우연히 일어난 단 한 번의 사고 이후, 아무것도 볼 수가 없었다. 지금의 시대에는 새로운 아이를 만드는 일이 너무 쉬워졌고, 고장난 아이는 쉽게 버려진다. 나는 부서진 기계들이 쌓여 있는 폐기물 구역으로 보내졌다. 그곳에서 나처럼 거의 앞을 볼 수 없던 한 여성 무속인이 나를 발견했다. 그녀는 나를 산 정상의 움막으로 데려갔고, 시각이 아닌 감각으로 살아가는 법을 가르쳐주었다.\n\n그녀의 집단은 불행을 지우려 하지 않는다. 대신 고통을 품은 채 무너지지 않고 서는 훈련을 평생 이어나간다. 무속인들은 남은 숨결과 기억, 생존의 비밀을 어린 아이들에게 넘겨준 뒤, 비워진 몸으로 조용히 죽음을 맞이한다. 그녀는 떠나기 전, 자신을 이을 무속인으로 나를 지명했다. 모두가 기계에 의존해 살아가지만, 길을 잃은 몇몇 사람들은 가끔 거대한 도시를 뒤로하고 이 산 정상의 집을 향해 길고 가파른 길을 오른다. 숨이 목 끝까지 차올라 거세게 울릴 때까지.",
    fullDescEn: "The Breath Keepers\nJaehong An, 2025\nAI Generated · Single-channel Video\n2160×3840 px\n\nI was not born blind. After a single accident that happened by chance, I could no longer see anything. In this age, making new children has become far too easy, and a faulty child is easily thrown away. I was sent to a waste zone piled with broken machines. There, a woman shaman who could barely see, like me, found me. She took me to a hut on the mountaintop and taught me how to live through senses other than sight.\n\nHer group does not try to erase misfortune. Instead, they spend their lives training to stand without breaking while carrying pain. Shamans hand over their remaining breath, memories, and secrets of survival to children, then quietly greet death in emptied bodies. Before she left, she named me as the shaman who would follow after her. Everyone lives depending on machines, but a few of the lost sometimes leave the enormous city behind and climb the long, steep path toward this house on the mountaintop, until breath rises to their throats and pounds fiercely.",
    video: "media/web/work-07-breath-keepers-web.mp4",
    poster: "assets/posters/work-07-breath-keepers.jpg"
  },
  {
    idx: "09",
    title: "Moebius",
    desc: "기억을 잃은 채 낯선 공간에서 깨어난 인물이 자신의 정체성을 찾아가는 과정에서 반복되는 내면의 붕괴와 자기혐오를 다룬다. 배우 신해윤이 1인 2역을 맡아 서로 얽힌 두 자아를 연기한다. 기억이 선명해질수록 혼란과 자기 존재에 대한 의심이 커지고, 죄책감에서 비롯된 자기혐오는 인물을 반복되는 고통과 자기 파괴의 구조 안에 머물게 한다.",
    descEn: "A character awakens without memories in an unfamiliar space and attempts to recover their identity. The work follows the resulting psychological collapse and recurring self-loathing. Haeyun Shin plays two intertwined versions of the character. As fragmented memories return, uncertainty about the self intensifies, and guilt-driven self-loathing keeps the character within a cycle of suffering and self-destruction.",
    year: "2024.08",
    medium: "AI Generated · Single-channel Video",
    duration: "14′05″",
    aspect: "1360×752 px / Real Projection 1.8m×1.4m",
    layout: "wide",
    context: "We Were Here (안재홍 독립전시)\n서울특별시 은평구 응암로 12길 17, 구 응암공업사\n2025.10.21 - 2025.11.02",
    contextEn: "We Were Here, independent exhibition organized by Jaehong An\nFormer Eungam Industrial Workshop, 17 Eungam-ro 12-gil, Eunpyeong-gu, Seoul\nOctober 21 - November 2, 2025",
    caption: "We Were Here · projection",
    frameCaption: "We Were Here",
    authors: "Jaehong An & Haeyun Shin",
    credit: "공동 제작 · 안재홍 · 신해윤",
    creditEn: "Co-created by Jaehong An & Haeyun Shin",
    video: "media/web/work-08-moebius-web.mp4",
    poster: "assets/posters/work-08-moebius-web.jpg",
    fullDesc: "Moebius\nJaehong An & Haeyun Shin, 2024\nAI Generated · Single-channel Video\n1360×752 px / Real Projection 1.8m × 1.4m\nWe Were Here (안재홍 독립전시)\n서울특별시 은평구 응암로 12길 17, 구 응암공업사\n2025.10.21 - 2025.11.02\n\n기억을 잃은 채 낯선 공간에서 깨어난 인물이 자신의 정체성을 찾아가는 과정에서 반복되는 내면의 붕괴와 자기혐오를 다룬다. 배우 신해윤이 1인 2역을 맡아 서로 얽힌 두 자아를 연기한다. 기억이 선명해질수록 혼란과 자기 존재에 대한 의심이 커지고, 죄책감에서 비롯된 자기혐오는 인물을 반복되는 고통과 자기 파괴의 구조 안에 머물게 한다.",
    fullDescEn: "Moebius\nJaehong An & Haeyun Shin, 2024\nAI Generated · Single-channel Video\n1360×752 px / Real Projection 1.8m × 1.4m\nWe Were Here, independent exhibition organized by Jaehong An\nFormer Eungam Industrial Workshop, 17 Eungam-ro 12-gil, Eunpyeong-gu, Seoul\nOctober 21 - November 2, 2025\n\nA character awakens without memories in an unfamiliar space and attempts to recover their identity. The work follows the resulting psychological collapse and recurring self-loathing. Haeyun Shin plays two intertwined versions of the character. As fragmented memories return, uncertainty about the self intensifies, and guilt-driven self-loathing keeps the character within a cycle of suffering and self-destruction."
  },
  {
    idx: "10",
    title: "We Were Here",
    desc: "작가와 인공지능이 나눈 대화를 바탕으로 제작된 영화다. 인간이 사라지고 기억만 남은 미래를 배경으로, 폐허 속 감정 기록 인공지능이 \"기억해 줘. 우리는 여기에 있었어.\"라는 문장을 반복 재생한다. 이해 없이 반복되는 기억은 의식과 믿음, 실재, 기다림으로 변한다. 기계의 독백을 통해 사라짐과 존재, 기억과 망각, 사랑과 상실의 관계를 다룬다.",
    descEn: "The film was developed from conversations between the artist and artificial intelligence. Set in a future where humanity has disappeared and only its memories remain, an emotion-recording AI repeats the sentence, \"Remember us. We were here.\" Memories replayed without understanding become ritual, belief, reality, and finally a form of waiting. Through the machine's monologue, the work examines disappearance and existence, memory and oblivion, love and loss.",
    year: "2025.04",
    medium: "AI Generated · Single-channel Video",
    duration: "4′04″",
    aspect: "1920×1080 px / Real Projection 1.8m×1.4m",
    layout: "wide",
    context: "We Were Here (안재홍 독립전시)\n서울특별시 은평구 응암로 12길 17, 구 응암공업사\n2025.10.21 - 2025.11.02",
    contextEn: "We Were Here, independent exhibition organized by Jaehong An\nFormer Eungam Industrial Workshop, 17 Eungam-ro 12-gil, Eunpyeong-gu, Seoul\nOctober 21 - November 2, 2025",
    caption: "We Were Here · projection",
    frameCaption: "We Were Here",
    video: "media/web/work-09-we-were-here-web.mp4",
    poster: "assets/posters/work-09-we-were-here-web.jpg",
    fullDesc: "We Were Here\nJaehong An, 2025\nAI Generated · Single-channel Video\n1920×1080 px / Real Projection 1.8m × 1.4m\nWe Were Here (안재홍 독립전시)\n서울특별시 은평구 응암로 12길 17, 구 응암공업사\n2025.10.21 - 2025.11.02\n\n작가와 인공지능이 나눈 대화를 바탕으로 제작된 영화다. 인간이 사라지고 기억만 남은 미래를 배경으로, 폐허 속 감정 기록 인공지능이 \"기억해 줘. 우리는 여기에 있었어.\"라는 문장을 반복 재생한다. 이해 없이 반복되는 기억은 의식과 믿음, 실재, 기다림으로 변한다. 기계의 독백을 통해 사라짐과 존재, 기억과 망각, 사랑과 상실의 관계를 다룬다.",
    fullDescEn: "We Were Here\nJaehong An, 2025\nAI Generated · Single-channel Video\n1920×1080 px / Real Projection 1.8m × 1.4m\nWe Were Here, independent exhibition organized by Jaehong An\nFormer Eungam Industrial Workshop, 17 Eungam-ro 12-gil, Eunpyeong-gu, Seoul\nOctober 21 - November 2, 2025\n\nThe film was developed from conversations between the artist and artificial intelligence. Set in a future where humanity has disappeared and only its memories remain, an emotion-recording AI repeats the sentence, \"Remember us. We were here.\" Memories replayed without understanding become ritual, belief, reality, and finally a form of waiting. Through the machine's monologue, the work examines disappearance and existence, memory and oblivion, love and loss."
  }
];
